"""empty message

Revision ID: f17566f5f04e
Revises: 
Create Date: 2023-04-16 07:04:25.491166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f17566f5f04e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('distance_from_earth_km', sa.Float(), nullable=True),
    sa.Column('mass_measured_in_earths', sa.Float(), nullable=True),
    sa.Column('volume_measured_in_earths', sa.Float(), nullable=True),
    sa.Column('mean_density_in_g_cm_cubed', sa.Float(), nullable=True),
    sa.Column('surface_gravity_in_m_squared', sa.Float(), nullable=True),
    sa.Column('escape_velocity_in_km_per_sec', sa.Float(), nullable=True),
    sa.Column('synodic_rotation_period_in_days', sa.Float(), nullable=True),
    sa.Column('temperature_in_k', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('passport', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('profile_pic', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('planet_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planet_comments')
    op.drop_table('users')
    op.drop_table('planets')
    # ### end Alembic commands ###