"""empty message

Revision ID: 9204e58b4476
Revises: 7a498e0790b9
Create Date: 2023-04-16 14:10:04.210380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9204e58b4476'
down_revision = '7a498e0790b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('spaceport_id', sa.Integer(), nullable=True),
    sa.Column('spacecraft_id', sa.Integer(), nullable=True),
    sa.Column('spacecraft_seat_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('flight_status_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['flight_status_id'], ['schedules.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.ForeignKeyConstraint(['spacecraft_id'], ['spacecrafts.id'], ),
    sa.ForeignKeyConstraint(['spacecraft_seat_id'], ['spacecraft_seats.id'], ),
    sa.ForeignKeyConstraint(['spaceport_id'], ['spaceports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights')
    # ### end Alembic commands ###