"""empty message

Revision ID: ce4eb3ae362e
Revises: 
Create Date: 2023-04-26 21:29:22.971802

"""
from alembic import op
import sqlalchemy as sa
import os

environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = 'ce4eb3ae362e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('distance_from_earth_km', sa.Float(), nullable=True),
    sa.Column('mass_measured_in_earths', sa.Float(), nullable=True),
    sa.Column('volume_measured_in_earths', sa.Float(), nullable=True),
    sa.Column('mean_density_in_g_cm_cubed', sa.Float(), nullable=True),
    sa.Column('surface_gravity_in_m_squared', sa.Float(), nullable=True),
    sa.Column('escape_velocity_in_km_per_sec', sa.Float(), nullable=True),
    sa.Column('synodic_rotation_period_in_days', sa.Float(), nullable=True),
    sa.Column('temperature_in_k', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spacecrafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('load_capacity_kg', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('height_m', sa.Float(), nullable=False),
    sa.Column('diameter_m', sa.Float(), nullable=False),
    sa.Column('mass_kg', sa.Float(), nullable=False),
    sa.Column('capsule_volume_m', sa.Float(), nullable=False),
    sa.Column('trunk_volume_m', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spaceports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('perks', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('perks')
    )
    op.create_table('travel_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('passport', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('profile_pic', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('frequent_flyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tier_id', sa.Integer(), nullable=True),
    sa.Column('account_no', sa.String(length=100), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tier_id'], ['tiers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('launch_spaceport_id', sa.Integer(), nullable=True),
    sa.Column('landing_spaceport_id', sa.Integer(), nullable=True),
    sa.Column('departure_time', sa.String(length=100), nullable=False),
    sa.Column('arrival_time', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['landing_spaceport_id'], ['spaceports.id'], ),
    sa.ForeignKeyConstraint(['launch_spaceport_id'], ['spaceports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spacecraft_seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spacecraft_id', sa.Integer(), nullable=False),
    sa.Column('travel_class_id', sa.Integer(), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['spacecraft_id'], ['spacecrafts.id'], ),
    sa.ForeignKeyConstraint(['travel_class_id'], ['travel_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('funds', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('spaceport_id', sa.Integer(), nullable=True),
    sa.Column('spacecraft_id', sa.Integer(), nullable=True),
    sa.Column('spacecraft_seat_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('flight_status_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['flight_status_id'], ['flight_status.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.ForeignKeyConstraint(['spacecraft_id'], ['spacecrafts.id'], ),
    sa.ForeignKeyConstraint(['spacecraft_seat_id'], ['spacecraft_seats.id'], ),
    sa.ForeignKeyConstraint(['spaceport_id'], ['spaceports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('seat_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('user_kg', sa.Float(), nullable=False),
    sa.Column('tax_percentage', sa.Float(), nullable=False),
    sa.Column('tax_total', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['seat_id'], ['spacecraft_seats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE flight_status SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE flights SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE frequent_flyers SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE planets SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE planet_comments SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE schedules SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE spacecrafts SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE spacecraft_seats SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE spaceports SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE tiers SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE transactions SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE travel_classes SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE wallets SET SCHEMA {SCHEMA};")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('flights')
    op.drop_table('wallets')
    op.drop_table('spacecraft_seats')
    op.drop_table('schedules')
    op.drop_table('planet_comments')
    op.drop_table('frequent_flyers')
    op.drop_table('users')
    op.drop_table('travel_classes')
    op.drop_table('tiers')
    op.drop_table('spaceports')
    op.drop_table('spacecrafts')
    op.drop_table('planets')
    op.drop_table('flight_status')
    # ### end Alembic commands ###