"""empty message

Revision ID: 788aec051296
Revises: f17566f5f04e
Create Date: 2023-04-16 07:18:25.666910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788aec051296'
down_revision = 'f17566f5f04e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spaceports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spaceports')
    # ### end Alembic commands ###