"""empty message

Revision ID: 18bae00a7a2e
Revises: 788aec051296
Create Date: 2023-04-16 13:15:00.040464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18bae00a7a2e'
down_revision = '788aec051296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spacecrafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('load_capacity_kg', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('height_m', sa.Float(), nullable=False),
    sa.Column('diameter_m', sa.Float(), nullable=False),
    sa.Column('mass_kg', sa.Float(), nullable=False),
    sa.Column('capsule_volume_m', sa.Float(), nullable=False),
    sa.Column('trunk_volume_m', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spacecrafts')
    # ### end Alembic commands ###