"""empty message

Revision ID: b4af644157b6
Revises: f6bfa65b1f94
Create Date: 2023-04-16 13:31:56.604109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4af644157b6'
down_revision = 'f6bfa65b1f94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spacecraft_seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spacecraft_id', sa.Integer(), nullable=False),
    sa.Column('travel_class_id', sa.Integer(), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['spacecraft_id'], ['spacecrafts.id'], ),
    sa.ForeignKeyConstraint(['travel_class_id'], ['travelclass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spacecraft_seats')
    # ### end Alembic commands ###